const BAD_REQUEST = 400;
const AUTHORIZATION_FAILURE = 401;
const NOT_FOUND = 404;
const DEFAULT = 500;
const DUPLICATE_USER = 1100;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT,
  DUPLICATE_USER,
  AUTHORIZATION_FAILURE,
};
