const BAD_REQUEST = 400;
const AUTHORIZATION_FAILURE = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const DUPLICATE_USER = 409;
const DEFAULT = 500;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT,
  DUPLICATE_USER,
  AUTHORIZATION_FAILURE,
  FORBIDDEN,
};
